# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SamplingPrior <- function(iter, NVer, NEd, PriorType, a, datafolder) {
    .Call(`_GraphMM_SamplingPrior`, iter, NVer, NEd, PriorType, a, datafolder)
}

